server:
  port: 7010

spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessSecret:
    bucketName:
