server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://user-service
          predicates:
            - Path=/user/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
